permissions:
  contents: write
name: Talkatone Update Workflow

on:
  schedule:
    - cron: '0 0 * * *' # 每天定时运行
  workflow_dispatch: # 手动触发

jobs:
  update_talkatone_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch the latest talkatone.list
      run: |
        curl -o talkatone.list https://raw.githubusercontent.com/SIJULY/Rules/main/Surge/talkatone.list

    - name: Modify and Append Header
      run: |
        mkdir -p Loon/plugin
        {
          echo '#!name = Talkatone';
          echo '#!desc = Talkatone分流。';
          echo '#!icon = https://raw.githubusercontent.com/HS-Case/Case/main/icon/Talkatone.png';
          echo '[Rule]';
          grep -v '^#' talkatone.list | sed '/^$/d' | sed 's/$/,DIRECT/';
          echo 'DOMAIN-KEYWORD,tktn.be,美国节点';
        } > Loon/plugin/Talkatone.plugin

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add Loon/plugin/Talkatone.plugin

        # 确保提交内容存在，否则跳过提交
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update Talkatone.plugin with latest rules and ,DIRECT"
          git push origin HEAD:main
        fi
